### ISSUE TITLE
Backend issue

### ISSUE THREAD

**Issue by saramohammadinejad** [mpi-sws-rse/ltltalk-interactive-synthesis#1]
Hi,

When I run ./interactive/run @mode=ltltalk for the backend part I receive the following error:

/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- execrunner (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from ./interactive/run:9:in `<main>'

I tried to resolve the error by installing other versions of ruby, but the issue still exists. Any suggestion?

Thanks,
Sara

**Comment by ivan-gavran** [comment]
Moved the issue to the backend repository --> https://github.com/mpi-sws-rse/ltltalk-backend/issues/1
